name: CI Pipeline

# Trigger the workflow on push to main branch or pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: shrutipatel
          POSTGRES_PASSWORD: password
          POSTGRES_DB: orders_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U shrutipatel" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Docker Buildx (used for multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub (if pushing to a registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image for the backend
      - name: Build Docker Image
        run: |
          docker build -t my-backend-image .

      # Run tests on the built image (assuming pytest is installed in the container)
      - name: Run Tests
        run: |
          docker run --rm my-backend-image pytest tests/

      # Health check on the application (optional but recommended)
      - name: Health Check
        run: |
          docker run --rm -d -p 8000:8000 my-backend-image
          sleep 10
          curl --fail http://localhost:8000/health || exit 1

