name: CI/CD Workflow

# Trigger this workflow on pull request (PR) and push to the main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Job to run tests on PR
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        run: |
          docker build -t orders_app .
          docker run --rm orders_app pytest

  # Job to build and deploy the Docker image
  deploy:
    needs: test  # Ensure tests pass before deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t your_dockerhub_username/orders_app .

      - name: Push Docker image
        run: |
          docker push your_dockerhub_username/orders_app:latest

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Pull the latest Docker image on EC2
            docker pull your_dockerhub_username/orders_app:latest

            # Stop and remove any existing containers
            docker stop order_app || true
            docker rm order_app || true

            # Run the new container
            docker run -d --name order_app -p 8000:8000 your_dockerhub_username/orders_app:latest
